<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Painel Sveltia</title>
    <script src="https://unpkg.com/@sveltia/cms/dist/sveltia-cms.js" type="module"></script>
  </head>
  <body>
    <script>
      // Ele inicia sozinho se encontrar a configuração em memória
      window.CMS_CONFIG = {
        backend: {
          name: "github",
          repo: "jhonatasdevc/receitas_teste",
          branch: "main"
        },
        media_folder: "public/images",
        public_folder: "/images",
        collections: [
          {
            name: "blog",
            label: "Blog de Teste",
            folder: "src/content/blog",
            create: true,
            fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Corpo", name: "body", widget: "markdown" }
            ]
          }
        ]
      };
    </script>
  </body>
</html>