# Remova ou comente o local_backend para não travar no servidor
# local_backend: true

logo_url: /logo.svg

backend:
  name: "github"
  repo: jhonatasdevc/receitas_teste  # 🌟 Troque aqui para o seu repositório
  branch: main
  # Este worker abaixo é um gateway de login público, pode mantê-lo para testar se ele está ativo!
  base_url: https://cms.majestico.workers.dev
  automatic_deployments: false

media_folder: "public/images"
public_folder: "/images"

# ... (mantenha o restante das coleções igual ao que enviou)
